### ISSUE TITLE
Issue with Installing "rgdal" Package for Lab 02

### ISSUE THREAD

**Issue by JessiMT** [Watts-College/cpp-526-sum-2024#11]
I'm getting an error when trying to call **library(rgdal)** in the provided template. Installing the three packages works fine, but the issue occurs when I run the RMD chunk for loading the "rgdal" library.

This is the message I get: "Error in library(rgdal) : there is no package called ‘rgdal’".

Is anyone else having the same issue?

Update: It seems that the rgdal package has been removed from the CRAN repository, but an older version can be downloaded from the archive on this website: https://cran.r-project.org/web/packages/rgdal/index.html

**Comment by gmcirco** [comment]
Thank you for bringing this to my attention. When the lab was originally created by the owner, the `rgdal` package was still in use. It has since been depricated in favor of other packages. I am looking into a solution currently. However, you should be able to complete the lab without installing rgdal. Just delete the lines with it.

If you cannot knit the file, just submit the .Rmd file and I will grade your code directly. I will also be addressing this in an email.

**Comment by anaitab** [comment]
I am using macOS Sonoma 14.5 with a M2 chip, and R studio 2024.04.1+748
I also got the message that  ‘rgdal’ is not available for these versions
I replaced 'rgdal' for  'sf'  which seems to have worked OK
