### ISSUE TITLE
casting function \

### ISSUE THREAD

**Issue by rubinaalmas** [Watts-College/cpp-526-sum-2024#12]
<img width="1470" alt="Screenshot 2024-05-19 at 8 18 34 PM" src="https://github.com/Watts-College/cpp-526-sum-2024/assets/169969012/8be19578-72c6-4c6f-b51b-1ed3afb31914">
hey everyone, I was just playing around with casting function and received this strange o/p . can someone help?

apparently, the o/p for grades was 5 7 ......
and then when i casted to numeric why did it change to 5 **8**.. and rest digits were same as the o/p

**Comment by gmcirco** [comment]
Good question!

The issue is because you are converting a numeric vector to a "factor". Factor variables are special in R because they encode a position into the categorical variable (for example, think a survey question). When you go from a factor to a numeric is will return the position, not the original number. Try this:

```
# returns the number
grades <- c("5","7","1","2","3")
as.numeric(grades)

# returns an ordered position
grades <- c("5","7","1","2","3")
grades <- as.factor(grades)
```

**Comment by rubinaalmas** [comment]
Ohhokay Now I get it. Thanks professor
